
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build --verbose > build.log
      - name: Upload build log
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
            message-path: build.log